name: OnCommit-Jenkins
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: '*Dev*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger OnCommit Jenkins
        uses: ftsamis/jenkins-githubaction@v2
        with:
          url: http://71.231.11.163:8080
          job_name: OnCommit
          username: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          start_timeout: "100"
          timeout: "1000"
          wait: true
