name: OnCommit-Jenkins

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch that includes 'Dev' in its name
  push:
    branches:
      - '*Dev*'
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Pull Request
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

  # This workflow contains a single job called "build"
  build:
    name: OnCommit
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Trigger OnCommit Jenkins
        uses: cameron-myers/jenkins-githubaction@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          url: http://71.231.11.163:8080
          job_name: OnCommit
          username: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          start_timeout: "100"
          timeout: "1000"
          wait: true
          parameters: '{"git_branch": "${{github.ref_name}}"}'
